# Generated by Django 4.0.1 on 2022-03-28 21:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=30)),
                ('student_image', models.ImageField(upload_to='media/student/')),
                ('student_email', models.EmailField(default='student@gmail.com', max_length=254)),
                ('student_mat_no', models.CharField(max_length=20)),
                ('student_phone_no', models.CharField(default='+234', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_username', models.CharField(max_length=30)),
                ('security_image', models.ImageField(upload_to='media/security')),
                ('security_email', models.EmailField(default='security@gmail.com', max_length=254)),
                ('security_phone_no', models.CharField(default='+234', max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100)),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='media/report/')),
                ('report_body', ckeditor.fields.RichTextField(default='Write some text here')),
                ('report_location', models.CharField(max_length=50)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_choice', models.CharField(choices=[('BSUM-1', 'S-One'), ('CHS', 'S-CHS'), ('BSUM-2', 'S-Two')], default='S-CHS', max_length=7)),
                ('report_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.student')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='media/post/')),
                ('post_slug', models.SlugField()),
                ('post_body', ckeditor.fields.RichTextField(default='Write some text here')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.student')),
            ],
        ),
    ]
